### ISSUE TITLE
Lab 3 - exercise 19 -- sales order not sent to credit management, unable to proceed with remainder of lab

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management#47]
# Module: 3
#### Step: 3

Description of issue - no opportunity to type into the reservation field.

![image](https://user-images.githubusercontent.com/89986870/183754414-157e2b79-680e-48c4-9025-531cd50f6ac5.png)

Repro steps:
- all previous tasks completely as per instructions without error. The screenshot below shows my screen upon completing initiating an outbound shipment - receive and confirm the sales order, step 15.
-
![image](https://user-images.githubusercontent.com/89986870/183754625-e98a64cd-a2d8-4652-b887-2ac6b3928c98.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by chaast** [comment]
has a pull request been initiated?

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 4 / Case study 3 / Exercise 19 Step 11. We are reviewing this and will provide an update once a resolution is in place.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
This issue has been tested several times. I was able to create the sales order from customer US-007 and confirm sales order. The sales order was not sent to credit management due to the order amount being less than or equal to the sales order exclusion amount in the sales order rule. 

![image](https://user-images.githubusercontent.com/104943975/221388635-c656be04-d9cf-47c1-ae4d-85a32733b4cb.png)

![image](https://user-images.githubusercontent.com/104943975/221388639-a5701554-1a9a-4ab5-b0f8-42164533cab1.png)

There's an exclusion on sales orders lesser than $10,000 for all customers. You can view blocking rules and exclusion rules on the Credit and collections > Setup > Credit management setup > Blocking rules page.

In the screenshot that you provided, I did not see the order line. The order line would need to be checked in the Sales order lines FastTab to view it in the Reservation form.

![image](https://user-images.githubusercontent.com/104943975/221389045-8610afe5-ffc0-443c-adee-288ae3a1c888.png)

**Comment by mstall1ngs** [comment]
> has a pull request been initiated?

No pull request has been initiated for this issue. Please view the above resolution.
